//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stenography.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stenography.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Able size for hide.
        /// </summary>
        public static string AbleSizeForHide {
            get {
                return ResourceManager.GetString("AbleSizeForHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program can write any file in another file with txt or png format. Another file needs to have enough space (a lot of text or big resolution)..
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File-container&apos;s path is wrong..
        /// </summary>
        public static string ContainerPathWrong {
            get {
                return ResourceManager.GetString("ContainerPathWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EngLangButton {
            get {
                return ResourceManager.GetString("EngLangButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file-container, which will contain secret file.
        /// </summary>
        public static string FDContainer {
            get {
                return ResourceManager.GetString("FDContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose output directory.
        /// </summary>
        public static string FDOutputDir {
            get {
                return ResourceManager.GetString("FDOutputDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose secret file.
        /// </summary>
        public static string FDSecret {
            get {
                return ResourceManager.GetString("FDSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file-container already contains secret file.
        /// </summary>
        public static string FDUnhideContainer {
            get {
                return ResourceManager.GetString("FDUnhideContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the file-container.
        /// </summary>
        public static string FileContainerPath {
            get {
                return ResourceManager.GetString("FileContainerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string HideButton {
            get {
                return ResourceManager.GetString("HideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiden.
        /// </summary>
        public static string Hiden {
            get {
                return ResourceManager.GetString("Hiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenOutDir {
            get {
                return ResourceManager.GetString("OpenOutDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter output filename.
        /// </summary>
        public static string OutputName {
            get {
                return ResourceManager.GetString("OutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose output directory.
        /// </summary>
        public static string OutputPath {
            get {
                return ResourceManager.GetString("OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output-file&apos;s path is wrong..
        /// </summary>
        public static string OutputPathWrong {
            get {
                return ResourceManager.GetString("OutputPathWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string PictureButton {
            get {
                return ResourceManager.GetString("PictureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with PNG.
        /// </summary>
        public static string PictureLabel {
            get {
                return ResourceManager.GetString("PictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary restart..
        /// </summary>
        public static string RestartWarning {
            get {
                return ResourceManager.GetString("RestartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string RusLangButton {
            get {
                return ResourceManager.GetString("RusLangButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose secret file.
        /// </summary>
        public static string SecretFile {
            get {
                return ResourceManager.GetString("SecretFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret-file&apos;s path is wrong..
        /// </summary>
        public static string SecretFilePathWrong {
            get {
                return ResourceManager.GetString("SecretFilePathWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret file is too big for file-conteiner..
        /// </summary>
        public static string SecretFileTooBig {
            get {
                return ResourceManager.GetString("SecretFileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sourse code:.
        /// </summary>
        public static string SourseCode {
            get {
                return ResourceManager.GetString("SourseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextButton {
            get {
                return ResourceManager.GetString("TextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with TXT.
        /// </summary>
        public static string TextLabel {
            get {
                return ResourceManager.GetString("TextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide.
        /// </summary>
        public static string UnhideButton {
            get {
                return ResourceManager.GetString("UnhideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide.
        /// </summary>
        public static string UnhideLabel {
            get {
                return ResourceManager.GetString("UnhideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhiden.
        /// </summary>
        public static string Unhiden {
            get {
                return ResourceManager.GetString("Unhiden", resourceCulture);
            }
        }
    }
}
